USE HEALTHCARETABLES;
-- Project Healthcare4 SQL CASE expression
-- PROBLEM 1
CREATE VIEW MEDICINETYPE AS
(
SELECT *, (CASE WHEN PRODUCTTYPE = 1 THEN "GENERIC"
				WHEN PRODUCTTYPE = 2 THEN "PATENT"
                WHEN PRODUCTTYPE = 3 THEN "REFERENCE"
                END) "TYPENAME" FROM MEDICINE WHERE TAXCRITERIA = "I" AND PRODUCTTYPE IN (1, 2, 3)
UNION
SELECT *, (CASE WHEN PRODUCTTYPE = 4 THEN "SIMILAR"
				WHEN PRODUCTTYPE = 5 THEN "NEW"
                WHEN PRODUCTTYPE = 6 THEN "SPECIFIC"
                END) "TYPENAME" FROM MEDICINE WHERE TAXCRITERIA = "II" AND PRODUCTTYPE IN (4, 5, 6)
);
SELECT * FROM MEDICINETYPE LIMIT 100;
SELECT ME.MEDICINEID, ME.PRODUCTNAME, ME.TYPENAME, ME.TAXCRITERIA FROM MEDICINETYPE ME INNER JOIN KEEP KE ON ME.MEDICINEID = KE.MEDICINEID
INNER JOIN PHARMACY PH ON KE.PHARMACYID = PH.PHARMACYID WHERE PH.PHARMACYNAME = "HEALTHDIRECT";

-- PROBLEM 2
SELECT PR.PRESCRIPTIONID, SUM(CO.QUANTITY) "TOTAL QUANTITY", (CASE WHEN SUM(CO.QUANTITY) < 20 THEN "LOW QUANTITY"
													WHEN COUNT(CO.QUANTITY) <= 49 THEN "MEDIUM QUANTITY"
                                                    WHEN COUNT(CO.QUANTITY) >= 50 THEN "HIGH QUANTITY"
                                                    END) "QUANTITY TAG"
FROM PRESCRIPTION PR INNER JOIN CONTAIN CO ON CO.PRESCRIPTIONID = PR.PRESCRIPTIONID
INNER JOIN PHARMACY PH ON PH.PHARMACYID = PR.PHARMACYID WHERE PH.PHARMACYNAME = "ALLY SCRIPTS" GROUP BY PR.PRESCRIPTIONID;

-- PROBLEM 3
SELECT KE.MEDICINEID, KE.QUANTITY, KE.DISCOUNT, "LOW HIGH" FROM KEEP KE INNER JOIN PHARMACY PH ON PH.PHARMACYID = KE.PHARMACYID
WHERE PH.PHARMACYNAME = "SPOT RX" AND KE.DISCOUNT>=30 GROUP BY KE.MEDICINEID HAVING KE.QUANTITY < 1000
UNION 
SELECT KE.MEDICINEID, KE.QUANTITY, KE.DISCOUNT, "HIGH ZERO" FROM KEEP KE INNER JOIN PHARMACY PH ON PH.PHARMACYID = KE.PHARMACYID
WHERE PH.PHARMACYNAME = "SPOT RX" AND KE.DISCOUNT = 0 GROUP BY KE.MEDICINEID HAVING KE.QUANTITY > 7500; 

-- PROBLEM 4
SET @AVG_MED  = (SELECT AVG(MAXPRICE) FROM MEDICINE);
SELECT PRODUCTNAME, MAXPRICE, "AFFORDABLE" FROM MEDICINE WHERE MAXPRICE<0.5*@AVG_MED AND HOSPITALEXCLUSIVE = "S"
UNION
SELECT PRODUCTNAME, MAXPRICE, "COSTLY" FROM MEDICINE WHERE MAXPRICE>2*@AVG_MED AND HOSPITALEXCLUSIVE = "S";

-- PROBLEM 5
SELECT PA.PATIENTID, PE.PERSONNAME, PA.DOB, PE.GENDER, (CASE WHEN PA.DOB < "1970-01-01" AND PE.GENDER = "MALE" THEN "ELDERMALE"
												  WHEN PA.DOB < "1970-01-01" AND PE.GENDER = "FEMALE" THEN "ELDERFEMALE"
                                                  WHEN PA.DOB < "1985-01-01" AND PE.GENDER = "MALE" THEN "MIDAGEMALE"
												  WHEN PA.DOB < "1985-01-01" AND PE.GENDER = "FEMALE" THEN "MIDAGEFEMALE"
                                                  WHEN PA.DOB < "2005-01-01" AND PE.GENDER = "MALE" THEN "ADULTMALE"
												  WHEN PA.DOB < "2005-01-01" AND PE.GENDER = "FEMALE" THEN "ADULTFEMALE"
                                                  WHEN PA.DOB >= "2005-01-01" AND PE.GENDER = "MALE" THEN "YOUNGMALE"
												  WHEN PA.DOB >= "2005-01-01" AND PE.GENDER = "FEMALE" THEN "YOUNGFEMALE" 
                                                  END) "CATEGORY"  FROM PATIENT PA INNER JOIN PERSON PE ON PE.PERSONID = PA.PATIENTID;