USE HEALTHCARETABLES;
-- Project Healthcare 11 SQL stored routines - 2
#PROBLEM 1
DROP PROCEDURE IF EXISTS PROB111;
DELIMITER $$
CREATE PROCEDURE PROB111 (MEDNAME VARCHAR(174))
BEGIN 
SELECT PH.PHARMACYNAME, PH.PHARMACYID FROM KEEP KE INNER JOIN PHARMACY PH ON PH.PHARMACYID = KE.PHARMACYID 
WHERE KE.MEDICINEID IN (SELECT MEDICINEID FROM MEDICINE WHERE PRODUCTNAME LIKE CONCAT("%", MEDNAME, "%"));
END $$
DELIMITER ;
CALL PROB111("OSTENAN");

#PROBLEM 2
DROP FUNCTION IF EXISTS PROB112;
DELIMITER $$
CREATE FUNCTION PROB112(PHID INT, YEAR1 VARCHAR(5))
RETURNS NUMERIC(20,5) DETERMINISTIC
BEGIN
DECLARE V1 NUMERIC;
SELECT AVERAGEPRICE INTO V1 FROM
(
SELECT PRESCRIPTIONID, PHARMACYID, AVG(TOTALPRICE)"AVERAGEPRICE", YEAR FROM
(
SELECT CO.PRESCRIPTIONID, PR.PHARMACYID, CO.QUANTITY*(SELECT MAXPRICE FROM MEDICINE WHERE MEDICINEID = CO.MEDICINEID) "TOTALPRICE", (SELECT YEAR(DATE) FROM TREATMENT WHERE TREATMENTID = (SELECT TREATMENTID FROM PRESCRIPTION WHERE PRESCRIPTIONID = CO.PRESCRIPTIONID)) "YEAR"
FROM CONTAIN CO INNER JOIN MEDICINE ME ON CO.MEDICINEID = ME.MEDICINEID
INNER JOIN PRESCRIPTION PR ON PR.PRESCRIPTIONID = CO.PRESCRIPTIONID
INNER JOIN TREATMENT TR ON TR.TREATMENTID = PR.TREATMENTID ORDER BY 1
) A GROUP BY PHARMACYID, YEAR ORDER BY 2
) B WHERE PHARMACYID = PHID AND YEAR = YEAR1;
RETURN V1;
END $$
DELIMITER ;
SELECT PROB112(5644, 2022) "AVG PRICE";

-- PROBLEM 3
DROP FUNCTION IF EXISTS PROB113;
DELIMITER $$
CREATE FUNCTION PROB113(STATE1 VARCHAR(5), YEAR1 VARCHAR(5))
RETURNS VARCHAR(100) DETERMINISTIC
BEGIN
DECLARE V1 VARCHAR(100);
SELECT DISEASENAME INTO V1 FROM 
(
SELECT DISEASENAME, CNT FROM 
(
SELECT AD.STATE, COUNT(TR.PATIENTID) "CNT", TR.DISEASEID, DI.DISEASENAME, YEAR(TR.DATE) "YEAR" FROM ADDRESS AD INNER JOIN PERSON PE ON PE.ADDRESSID = AD.ADDRESSID
INNER JOIN TREATMENT TR ON TR.PATIENTID = PE.PERSONID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID GROUP BY AD.STATE, TR.DISEASEID, YEAR ORDER BY 5, 1
) A WHERE STATE = STATE1 AND YEAR = YEAR1 ORDER BY 2 DESC
) B LIMIT 1;
RETURN V1;
END $$
DELIMITER ;
SELECT PROB113("AL", 2019) "DISEASE NAME";

-- PROBLEM 4
DROP FUNCTION IF EXISTS PROB114;
DELIMITER $$
CREATE FUNCTION PROB114(CITY1 VARCHAR(50), DISEASE1 VARCHAR(50), YEAR1 VARCHAR(5))
RETURNS INT DETERMINISTIC
BEGIN
DECLARE V1 INT;
SELECT CNT INTO V1 FROM
(
SELECT COUNT(TR.PATIENTID) "CNT", AD.CITY, DI.DISEASENAME, YEAR(TR.DATE) "YEAR" FROM ADDRESS AD INNER JOIN PERSON PE ON PE.ADDRESSID = AD.ADDRESSID
INNER JOIN TREATMENT TR ON TR.PATIENTID = PE.PERSONID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID
GROUP BY AD.CITY, DI.DISEASENAME, YEAR ORDER BY 2,3,4
) A WHERE CITY = CITY1 AND DISEASENAME = DISEASE1 AND YEAR = YEAR1;
RETURN V1;
END $$
DELIMITER ;
SELECT PROB114("Anchorage", "Epilepsy", "2020") "COUNT OF PEOPLE";

-- PROBLEM 5
DROP FUNCTION IF EXISTS PROB115;
DELIMITER $$
CREATE FUNCTION PROB115(ISCOMPANY VARCHAR(100))
RETURNS NUMERIC(20,5) DETERMINISTIC
BEGIN
DECLARE V1 NUMERIC(20,5);
SELECT AVGBALANCE INTO V1 FROM
(
SELECT IC.COMPANYNAME, AVG(CL.BALANCE) "AVGBALANCE" FROM INSURANCECOMPANY IC INNER JOIN INSURANCEPLAN IP ON IP.COMPANYID = IC.COMPANYID	
INNER JOIN CLAIM CL ON CL.UIN = IP.UIN
INNER JOIN TREATMENT TR ON CL.CLAIMID = TR.CLAIMID WHERE YEAR(TR.DATE) = "2022" GROUP BY IC.COMPANYNAME
) A WHERE COMPANYNAME = ISCOMPANY;
RETURN V1;
END $$
DELIMITER ;
SELECT PROB115("Star Health and Allied Insurrance Co.") "AVERAGE BALANCE";