USE HEALTHCARETABLES;
-- Project Healthcare1 problem statements
-- PROBLEM 1   
SELECT COUNT(*) "CNT", (CASE WHEN TIMESTAMPDIFF(YEAR, P.DOB, CURDATE()) <=14 THEN "CHILDREN"
			 WHEN TIMESTAMPDIFF(YEAR, P.DOB, CURDATE()) <=25 THEN "YOUTH"
             WHEN TIMESTAMPDIFF(YEAR, P.DOB, CURDATE()) <=64 THEN "ADULTS"
             WHEN TIMESTAMPDIFF(YEAR, P.DOB, CURDATE()) >=65 THEN "SENIORS"
		     END) "CATEGORY" FROM PATIENT P INNER JOIN TREATMENT T ON P.PATIENTID = T.PATIENTID AND YEAR(T.DATE)=2022 GROUP BY CATEGORY ;
-- PROBLEM 2
WITH CTE AS  
(SELECT DI.DISEASENAME "DISEASENAME", TR.DISEASEID, COUNT(PA.PATIENTID) "COUNTGENDER", PE.GENDER "GENDER" FROM PATIENT PA INNER JOIN PERSON PE ON PA.PATIENTID = PE.PERSONID
INNER JOIN TREATMENT TR ON PA.PATIENTID = TR.PATIENTID INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID GROUP BY TR.DISEASEID, PE.GENDER)
SELECT DISEASENAME, (SELECT COUNTGENDER FROM CTE WHERE GENDER = "MALE" AND DISEASENAME = C.DISEASENAME)/(SELECT COUNTGENDER FROM CTE WHERE GENDER = "FEMALE" AND DISEASENAME = C.DISEASENAME) "RATIO" FROM CTE C  GROUP BY DISEASENAME ORDER BY RATIO DESC ;

-- PROBLEM 3
SELECT PE.GENDER "GENDER", COUNT(TR.TREATMENTID) "TREATMENT COUNT", COUNT(TR.CLAIMID) "CLAIM COUNT", COUNT(TR.TREATMENTID)/COUNT(TR.CLAIMID) "RATION" 
FROM PERSON PE INNER JOIN TREATMENT TR ON PE.PERSONID = TR.PATIENTID GROUP BY PE.GENDER;

-- PROBLEM 4
SELECT PHARMACYID, SUM(TOTALPRICE), SUM(DISCOUNTPRICE) 
FROM (
SELECT K.PHARMACYID, K.MEDICINEID, K.QUANTITY, K.QUANTITY*(SELECT MAXPRICE FROM MEDICINE WHERE MEDICINEID = K.MEDICINEID) "TOTALPRICE",
K.QUANTITY*(SELECT MAXPRICE FROM MEDICINE WHERE MEDICINEID = K.MEDICINEID) - K.DISCOUNT*(K.QUANTITY*(SELECT MAXPRICE FROM MEDICINE WHERE MEDICINEID = K.MEDICINEID))/100 "DISCOUNTPRICE"
FROM KEEP K INNER JOIN MEDICINE M ON K.MEDICINEID = M.MEDICINEID
) A GROUP BY PHARMACYID ORDER BY PHARMACYID;

-- PROBLEM 5
SELECT PHARMACYNAME, MAX(CNT), MIN(CNT), AVG(CNT)
FROM( 
SELECT PR.PRESCRIPTIONID, PH.PHARMACYNAME, COUNT(DISTINCT(C.MEDICINEID)) "CNT" FROM PHARMACY PH INNER JOIN PRESCRIPTION PR ON PH.PHARMACYID = PR.PHARMACYID
INNER JOIN CONTAIN C ON C.PRESCRIPTIONID = PR.PRESCRIPTIONID GROUP BY PR.PRESCRIPTIONID
) A GROUP BY PHARMACYNAME;