USE HEALTHCARETABLES;
-- Project Healthcare9 SQL rollup
-- PROBLEM 1
SELECT IFNULL(AD.STATE, 'TOTAL') STATE, IFNULL(PE.GENDER, "TOTALGEN") "GENDER", COUNT(PE.PERSONID) FROM ADDRESS AD INNER JOIN PERSON PE ON AD.ADDRESSID = PE.ADDRESSID
INNER JOIN TREATMENT TR ON TR.PATIENTID = PE.PERSONID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID WHERE DI.DISEASENAME = "AUTISM" GROUP BY AD.STATE, PE.GENDER WITH ROLLUP;

-- PROBLEM 2
SELECT  IFNULL(IP.PLANNAME,"TOTAL") "PLANNAME", IC.COMPANYNAME, IFNULL(YEAR(TR.DATE), "TOTAL-3-YEAR") "YEAR", COUNT(TR.TREATMENTID) FROM INSURANCECOMPANY IC INNER JOIN INSURANCEPLAN IP ON IC.COMPANYID = IP.COMPANYID
INNER JOIN CLAIM CL ON CL.UIN = IP.UIN
INNER JOIN TREATMENT TR ON TR.CLAIMID = CL.CLAIMID WHERE YEAR(TR.DATE) IN ('2020', '2021', '2022') GROUP BY IP.PLANNAME, YEAR(TR.DATE) WITH ROLLUP;

-- PROBLEM 3
DROP VIEW IF EXISTS PROB093;
CREATE VIEW PROB093 AS
(
SELECT AD.STATE, DI.DISEASENAME, COUNT(TR.TREATMENTID) "COUNT1", DENSE_RANK() OVER(PARTITION BY AD.STATE ORDER BY COUNT(TR.TREATMENTID)) "DENSE"
FROM ADDRESS AD INNER JOIN PERSON PE ON PE.ADDRESSID = AD.ADDRESSID
INNER JOIN TREATMENT TR ON TR.PATIENTID = PE.PERSONID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID
WHERE YEAR(TR.DATE) = '2022' GROUP BY AD.STATE, DI.DISEASENAME
);
SELECT IFNULL(STATE, "TOTAL") "STATE", DISEASENAME, COUNT1 FROM PROB093 PRO WHERE DENSE IN (1, (SELECT MAX(DENSE) FROM PROB093 WHERE STATE = PRO.STATE)) GROUP BY STATE, DISEASENAME WITH ROLLUP;

-- PROBLEM 4
DROP VIEW IF EXISTS PROB094;
CREATE VIEW PROB094 AS
( 
SELECT PH.PHARMACYNAME, DI.DISEASENAME, COUNT(PR.PRESCRIPTIONID) "COUNT1" FROM PHARMACY PH INNER JOIN PRESCRIPTION PR ON PH.PHARMACYID = PR.PHARMACYID 
INNER JOIN TREATMENT TR ON TR.TREATMENTID = PR.TREATMENTID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID
WHERE YEAR(TR.DATE) = "2022" GROUP BY PH.PHARMACYNAME, DI.DISEASENAME
);
SELECT PHARMACYNAME, SUM(COUNT1) "TOTAL PRESCRIPTIONS" FROM PROB094 GROUP BY PHARMACYNAME ORDER BY 1;
SELECT DISEASENAME, SUM(COUNT1) "TOTAL PRESCRIPTIONS" FROM PROB094 GROUP BY DISEASENAME ORDER BY 1;

-- PROBLEM 5
SELECT IFNULL(DI.DISEASENAME, "TOTAL") "DISEASENAME" , PE.GENDER, COUNT(PE.PERSONID) "COUNT" FROM PERSON PE INNER JOIN TREATMENT TR ON TR.PATIENTID = PE.PERSONID
INNER JOIN DISEASE DI ON DI.DISEASEID = TR.DISEASEID WHERE YEAR(TR.DATE) = "2022" GROUP BY DI.DISEASENAME, PE.GENDER WITH ROLLUP;