USE HEALTHCARETABLES;
-- Project Healthcare3 problem statements
-- PROBLEM 1
SELECT PR.PHARMACYID, COUNT(C.MEDICINEID) FROM PRESCRIPTION PR INNER JOIN CONTAIN C ON  PR.PRESCRIPTIONID = C.PRESCRIPTIONID 
INNER JOIN MEDICINE M ON C.MEDICINEID = M.MEDICINEID INNER JOIN TREATMENT T ON T.TREATMENTID = PR.TREATMENTID 
WHERE M.HOSPITALEXCLUSIVE= "S" AND YEAR(T.DATE) IN("2021", "2022") GROUP BY PR.PHARMACYID ORDER BY 2 DESC;

-- PROBLEM 2
SELECT IC.COMPANYNAME, IP.PLANNAME, COUNT(TR.CLAIMID) FROM INSURANCEPLAN IP INNER JOIN INSURANCECOMPANY IC ON IP.COMPANYID = IC.COMPANYID
INNER JOIN CLAIM CL ON IP.UIN = CL.UIN
INNER JOIN TREATMENT TR ON CL.CLAIMID = TR.CLAIMID GROUP BY IC.COMPANYNAME, IP.PLANNAME ORDER BY 1; 

-- PROBLEM 3
CREATE VIEW INSURANCEREPORT AS
( 
SELECT IC.COMPANYNAME, IP.PLANNAME, COUNT(TR.TREATMENTID) "CNT", DENSE_RANK() OVER(PARTITION BY IC.COMPANYNAME ORDER BY COUNT(TR.TREATMENTID)) "DENSERANK"
FROM INSURANCEPLAN IP INNER JOIN INSURANCECOMPANY IC ON IP.COMPANYID = IC.COMPANYID 
INNER JOIN CLAIM CL ON IP.UIN = CL.UIN
INNER JOIN TREATMENT TR ON CL.CLAIMID = TR.CLAIMID GROUP BY IC.COMPANYNAME, IP.PLANNAME ORDER BY 1, 3);

SELECT COMPANYNAME, (SELECT PLANNAME FROM INSURANCEREPORT A WHERE CNT = (SELECT MAX(CNT) FROM INSURANCEREPORT WHERE COMPANYNAME = A.COMPANYNAME) AND COMPANYNAME = B.COMPANYNAME LIMIT 1) "MAX CLAIMED", 
(SELECT PLANNAME FROM INSURANCEREPORT A WHERE CNT = (SELECT MIN(CNT) FROM INSURANCEREPORT WHERE COMPANYNAME = A.COMPANYNAME) AND COMPANYNAME = B.COMPANYNAME LIMIT 1) "LEAST CLAIMED" FROM INSURANCEREPORT B GROUP BY COMPANYNAME;  

-- PROBLEM 4
CREATE VIEW STATEPATIENT AS
(
SELECT AD.STATE, COUNT(PA.PATIENTID) "CNT1" FROM ADDRESS AD INNER JOIN PERSON PE ON AD.ADDRESSID = PE.ADDRESSID 
INNER JOIN PATIENT PA ON PA.PATIENTID = PE.PERSONID GROUP BY AD.STATE
);
SELECT * FROM STATEPATIENT;

CREATE VIEW STATEPERSON AS
(
SELECT AD.STATE, COUNT(PE.PERSONID) "CNT2" FROM ADDRESS AD INNER JOIN PERSON PE ON AD.ADDRESSID = PE.ADDRESSID GROUP BY AD.STATE
);
SELECT * FROM STATEPERSON;

SELECT SPA.STATE, CNT2/CNT1 "PEO:PAT" FROM STATEPATIENT SPA INNER JOIN STATEPERSON SPE ON SPA.STATE = SPE.STATE;
 
-- PROBLEM 5
SELECT PH.PHARMACYNAME, SUM(CO.QUANTITY) "MEDICINE QUANTITY" 
FROM ADDRESS AD INNER JOIN PHARMACY PH ON AD.ADDRESSID = PH.ADDRESSID
INNER JOIN PRESCRIPTION PR ON PR.PHARMACYID = PH.PHARMACYID
INNER JOIN CONTAIN CO ON PR.PRESCRIPTIONID = CO.PRESCRIPTIONID
INNER JOIN TREATMENT TR ON TR.TREATMENTID = PR.TREATMENTID
INNER JOIN MEDICINE ME ON ME.MEDICINEID = CO.MEDICINEID
WHERE YEAR(TR.DATE) = "2021" AND ME.TAXCRITERIA = "I" AND AD.STATE = "AZ" GROUP BY PH.PHARMACYNAME ORDER BY 1;